feat: add toggle component
hooroo/roo-ui pull request #392
Opened 2021-07-23 05:34 UTC by ajlu

## Description

Add Toggle component (used to toggle **Use points** in Qantas Holidays)
- Toggle on design: https://www.figma.com/file/XBNVT7rT1JOBPslS03pkTU/%F0%9F%94%A5-EPIC-Encourage-Points-Burn?node-id=1090%3A75856 
- Toggle off design: https://www.figma.com/file/XBNVT7rT1JOBPslS03pkTU/%F0%9F%94%A5-EPIC-Encourage-Points-Burn?node-id=1071%3A75791

💁‍

## Related issues

💪

## Looks like this

![Screen Shot 2021-07-23 at 3 33 16 pm](https://user-images.githubusercontent.com/8179300/126741072-21fafe62-fe88-4848-8e38-b95ccdeb1c9d.png)

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [ ] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Angus](https://github.com/angusfretwell), [Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), or [Long](https://github.com/KieraDOG)).
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [ ] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

2021-07-23 05:34 UTC, ehyland commented
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: f55f703e30e4fa4ab16316b29fd7aa13edfa1f73

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/60fa55000e3da10008f80e5e](https://app.netlify.com/sites/roo-ui/deploys/60fa55000e3da10008f80e5e?utm_source=github&utm_campaign=bot_dl)

2021-07-23 05:59 UTC, KieraDOG approved these changes
LGTM 👍

2021-07-26 00:51 UTC, philipwindeyer requested changes
Niiiice 🤙  LGTM

Just missing one thing; the typedef for TypeScript projects within the org.
Component definitions live here: https://github.com/hooroo/roo-ui/blob/master/src/components/index.d.ts

If I had to guess, the `Radio` and ` Checkbox` definitions are probably the closest to what the def might look like for this

2021-07-26 01:13 UTC, philipwindeyer approved these changes
LGTM 🚀

2021-07-26 01:26 UTC, mrm007 commented on src/components/Toggle/Toggle.js
> +  height: 0;
I would recommend [`hideVisually`](https://polished.js.org/docs/#hidevisually) instead ([why]).

[why]: https://snook.ca/archives/html_and_css/hiding-content-for-accessibility

2021-07-26 01:28 UTC, eneo5541 approved these changes
LGTM!

2021-07-26 01:43 UTC, ajlu commented on src/components/Toggle/Toggle.js
> +  height: 0;
Thanks! updated 😄

2021-07-26 03:57 UTC, Anthropic approved these changes

2021-07-26 04:03 UTC, merged

2021-07-26 04:08 UTC, angusfretwell commented
:tada: This PR is included in version 0.94.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/roo-ui/v/0.94.0)
- [GitHub release](https://github.com/hooroo/roo-ui/releases/tag/v0.94.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: