feat(breakpoints): update breakpoints & maxWidth
hooroo/roo-ui pull request #394
Opened 2021-08-05 07:15 UTC by apisani

### Updated breakpoints & maxWidth

Breakpoints and maxWidth values have been udpated.

2021-08-05 07:16 UTC, ehyland commented
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: 758b243f35ef22fe3312e790d8786c0ff498f1d8

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/610b902f48c89d0008603b58](https://app.netlify.com/sites/roo-ui/deploys/610b902f48c89d0008603b58?utm_source=github&utm_campaign=bot_dl)

2021-08-05 08:19 UTC, Anthropic approved these changes

2021-08-05 08:24 UTC, Anthropic requested changes
Can you update the Hide component tests to use the same breakpoints as the theme?

2021-08-05 08:33 UTC, Anthropic approved these changes

2021-08-08 23:20 UTC, mrm007 approved these changes

2021-08-25 00:46 UTC, merged

2021-08-25 00:52 UTC, qh-deploy-user commented
:tada: This PR is included in version 0.97.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/roo-ui/v/0.97.0)
- [GitHub release](https://github.com/hooroo/roo-ui/releases/tag/v0.97.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: