Tooltip component
hooroo/roo-ui pull request #409
Opened 2021-09-04 23:37 UTC by klubiniecki-qantas

## Description

Added `<Tooltip />` component

💁‍

## Related issues

https://app.clubhouse.io/qantasaccommodation/story/76995/tooltip

💪

## Looks like this

![Screen Shot 2021-09-05 at 9 36 22 am](https://user-images.githubusercontent.com/60587157/132110442-b5f2dab1-3d62-4ab8-bfe0-6abb5eb4b300.png)

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), [Marcel](https://github.com/Anthropic), [Sam](https://github.com/SamuSan) [Long](https://github.com/KieraDOG)) or a Roo UI working-group human.
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

2021-09-04 23:43 UTC, ehyland commented
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: c58260e50ef62b2fce9174c4f262e83512408138

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/61340344c5c34a0008b38623](https://app.netlify.com/sites/roo-ui/deploys/61340344c5c34a0008b38623?utm_source=github&utm_campaign=bot_dl)

2021-09-04 23:45 UTC, ehyland commented
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: 86071e26056433407a4fe9da3824ff765b66c7af

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/61340384cf596c00070aec2d](https://app.netlify.com/sites/roo-ui/deploys/61340384cf596c00070aec2d?utm_source=github&utm_campaign=bot_dl)

2021-09-05 22:27 UTC, memcc reviewed
Hey mate - looking great so far!  Few issues / questions - ping me if you wanna chat about them :)

2021-09-05 22:27 UTC, memcc commented on src/components/Tooltip/Tooltip.js
> +        </NakedButton>
issue: it looks like the close button is not center aligned

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/13717241/132142901-fa8d7a37-3e68-47c2-857f-c082118bcb35.png">

2021-09-05 22:27 UTC, memcc commented on src/components/Tooltip/Tooltip.js
> +Tooltip.displayName = 'Tooltip';
suggestion: you can remove `displayName` here.

2021-09-05 22:27 UTC, memcc commented on src/theme.js
> +  mint: '#BFF4F2',
question: should we be aligning with Runway on colour names - they named this `bayBlue30`

2021-09-05 23:33 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +Tooltip.displayName = 'Tooltip';
Cool, I'll remove it!

2021-09-05 23:33 UTC, klubiniecki-qantas commented on src/theme.js
> +  mint: '#BFF4F2',
No idea, I googled the name of this colour and `mint` came up 😄

2021-09-05 23:51 UTC, ajlu commented on src/components/Tooltip/Tooltip.js
> +  onClose: null,
use `() => {}` instead for same type?

2021-09-05 23:51 UTC, ajlu commented on src/components/Tooltip/README.md
> +| `pointingDirection` | Pointer direction                   | `One of: top, bottom, left, right` | `top`   | no        |
rename `pointingDirection` to `pointerDirection` for consistency?

2021-09-06 00:09 UTC, philipwindeyer commented on src/theme.js
> +  mint: '#BFF4F2',
Good point though - historically all these colour names align with Qantas colour scheme names, and now in Runway as well

2021-09-06 00:09 UTC, philipwindeyer commented on src/components/index.d.ts
> +  export const Tooltip: SC.StyledComponent<TooltipProps, TooltipProps, any>;
👏

2021-09-06 00:14 UTC, philipwindeyer approved these changes
LGTM 🚀  aside from those couple of comments already here (I'd also use the `pointer` prefix for consistency on direction and position). And re colour names, the colours and their names in roo-ui, hotels self-service and extranet historically originated directly from Qantas' colour palette. Although we may have potentially diverged - not sure how strongly we all feel about this

2021-09-06 00:31 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +      })}
Please add a semicolon here otherwise it might break formatting. 

```suggestion
      })};
```

In general, add a semicolon after every mixin block.

2021-09-06 00:32 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +const pointerHeight = '8px';
We should probably use `rem`s, right?

```suggestion
import { rem, triangle } from 'polished';
import { Box, NakedButton, Icon } from '../';

const pointerWidth = rem(16);
const pointerHeight = rem(8);
```

2021-09-06 00:36 UTC, klubiniecki-qantas commented on src/components/Tooltip/README.md
> +| `pointingDirection` | Pointer direction                   | `One of: top, bottom, left, right` | `top`   | no        |
👍

2021-09-06 00:36 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +      })}
👍

2021-09-06 00:37 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +const pointerHeight = '8px';
👍

2021-09-06 00:39 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +  position: 'relative',
Looks like this might break if `position` is overriden, e.g.

```jsx
<Tooltip /* required props */ position="absolute" />
```

## `position: absolute`
![position absolute](https://user-images.githubusercontent.com/3297808/132146073-39cecf97-2f97-45f6-8e43-8dd47b09a74f.png)

## `position: relative`

![position relative](https://user-images.githubusercontent.com/3297808/132146097-31293e18-7ce9-4ada-a2f1-d2e3f715ac6a.png)



But why does `position` need to be a prop?

2021-09-06 00:48 UTC, mrm007 commented on src/components/Tooltip/Tooltip.test.js
> +      mountWithTheme(<Tooltip pointerPosition="20%">Save 45%</Tooltip>, theme);
The description doesn't match what's being tested.

2021-09-06 00:50 UTC, mrm007 commented on src/components/Tooltip/Tooltip.test.js
> +        <Tooltip pointingDirection="left">Save 45%</Tooltip>,
Please test all values so all code paths are tested.

```suggestion
  it.each(['top', 'right', 'bottom', 'left'])('renders different pointing direction: %s', (direction) => {
```    const render = () =>
      mountWithTheme(
        <Tooltip pointingDirection={direction}>Save 45%</Tooltip>,
```

2021-09-06 00:56 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +  background-color: ${({ colorMode }) => getColor(colorMode)};
Why isn't this `getColor` using the theme?

2021-09-06 00:58 UTC, mrm007 commented on src/components/Tooltip/Tooltip.story.js
> +          onClose={boolean('With Close button', false)}
![onClose boolean](https://user-images.githubusercontent.com/3297808/132146853-9fceebb1-4cb8-4246-a233-7976724253ef.png)

2021-09-06 01:00 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +  onClose: null,
👍

2021-09-06 01:01 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +            color={colorMode === 'dark' && 'white'}
`color={false}` isn't a valid prop for this component.

![image](https://user-images.githubusercontent.com/3297808/132147000-b2cac2d8-5127-4d7b-95ea-d3ca7114b002.png)

2021-09-06 01:02 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +  position: 'relative',
I don't think it needs to be, I just grabbed this bit from Hotels code. Will remove it.

2021-09-06 01:19 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +            color={colorMode === 'dark' && 'white'}
👍

2021-09-06 01:19 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.story.js
> +          onClose={boolean('With Close button', false)}
👍

2021-09-06 01:26 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +  background-color: ${({ colorMode }) => getColor(colorMode)};
Good point, I missed that one.

2021-09-06 01:27 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.test.js
> +      mountWithTheme(<Tooltip pointerPosition="20%">Save 45%</Tooltip>, theme);
🤦

2021-09-06 01:31 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.test.js
> +        <Tooltip pointingDirection="left">Save 45%</Tooltip>,
🚀

2021-09-06 01:59 UTC, ajlu requested changes

2021-09-06 01:59 UTC, ajlu commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
`onClose` default prop missing? On another note, lint doesn't pick this up?

2021-09-06 02:25 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
The prop is optional, so no point in having a default value of `null`. The rule is not on by default, and IMHO we shouldn't enable it.

2021-09-06 02:57 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
@ajlu suggested we add is with `undefined`. @mrm007 what do you think?

2021-09-06 03:33 UTC, mrm007 commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
But why though? `props.onClose` is `undefined` regardless.

2021-09-06 03:40 UTC, ajlu commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
I would say I'm used to the rule being on and like how it will consistently show what the value is when the prop is provided or not, but happy with either

2021-09-06 03:41 UTC, ajlu approved these changes

2021-09-06 03:43 UTC, klubiniecki-qantas commented on src/components/Tooltip/Tooltip.js
> +  colorMode: 'light',
Let's leave it as is, it will (if nothing else) be aligned with other components in RooUI.

2021-09-06 03:44 UTC, merged

2021-09-16 23:58 UTC, qh-deploy-user commented
:tada: This PR is included in version 0.99.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/roo-ui/v/0.99.0)
- [GitHub release](https://github.com/hooroo/roo-ui/releases/tag/v0.99.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2021-09-17 00:13 UTC, mrm007 commented
@klubiniecki-qantas next time you merge to master remember to tag your commits so a release is created https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming