feat: added ArrowControl component
hooroo/roo-ui pull request #418
Opened 2021-10-01 03:37 UTC by klubiniecki-qantas

## Description

Added ArrowControl component for image gallery controls.

💁‍

## Looks like this

![Screen Shot 2021-10-01 at 1 37 03 pm](https://user-images.githubusercontent.com/60587157/135561486-c411d4a9-2ba6-456a-9e0a-f385ded4c80c.png)

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [x] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), [Marcel](https://github.com/Anthropic), [Sam](https://github.com/SamuSan) [Long](https://github.com/KieraDOG)) or a Roo UI working-group human.
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [x] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

2021-10-01 03:37 UTC, ehyland commented
👷 Deploy Preview for *roo-ui* processing.


🔨 Explore the source changes: b77eaaa784a6eab5f7e5b5ebab6e8fae377068cb

🔍 Inspect the deploy log: [https://app.netlify.com/sites/roo-ui/deploys/61568292d918230008674e7c](https://app.netlify.com/sites/roo-ui/deploys/61568292d918230008674e7c?utm_source=github&utm_campaign=bot_dl)

2021-10-01 03:43 UTC, apalski commented on src/components/ArrowControl/ArrowControl.js
> +    border-radius: 50%;
suggestion: to use the theme value for this:
`border-radius: ${themeGet('radii.rounded')};`

2021-10-01 03:44 UTC, KieraDOG requested changes

2021-10-01 03:44 UTC, KieraDOG commented on src/components/ArrowControl/ArrowControl.js
> +  `;
We should always declare styled component outside of component

2021-10-01 03:51 UTC, klubiniecki-qantas commented on src/components/ArrowControl/ArrowControl.js
> +    border-radius: 50%;
Will do!

2021-10-01 03:51 UTC, klubiniecki-qantas commented on src/components/ArrowControl/ArrowControl.js
> +  `;
👍

2021-10-01 03:55 UTC, apalski commented on src/components/ArrowControl/ArrowControl.js
> +    border-radius: 50%;
Maybe consider the aria-controls [(https://www.w3.org/TR/wai-aria-practices-1.2/#button)]

2021-10-01 03:56 UTC, apalski approved these changes
Looks great 👍  just a couple of comments

2021-10-01 04:26 UTC, KieraDOG approved these changes

2021-10-03 23:48 UTC, merged

2021-10-03 23:52 UTC, qh-deploy-user commented
:tada: This PR is included in version 0.101.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/roo-ui/v/0.101.0)
- [GitHub release](https://github.com/hooroo/roo-ui/releases/tag/v0.101.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: