feat: tertiary button
hooroo/roo-ui pull request #458
Opened 2021-12-09 05:48 UTC by paul-corbett-qantas

## Description

[](https://app.shortcut.com/qantasaccommodation/story/78312/tertiary-button)

💁‍

## Related issues

💪

## Looks like this

🤨

---

**PR check-list**

🚨 **IMPORTANT:** Please review the [guidelines for contributing](./CONTRIBUTING.md) to this repository first! 👀

- [ ] You've requested a review from at least ONE person. Preferably a roo-ui maintainer ([Philip](https://github.com/philipwindeyer), [Eric](https://github.com/eneo5541), [Mike](https://github.com/memcc), [Marcel](https://github.com/Anthropic), [Sam](https://github.com/SamuSan) [Long](https://github.com/KieraDOG)) or a Roo UI working-group human.
  - Note: If your PR has not been reviewed within two days of requesting a review, feel free to seek reviews from other [team members of Qantas Hotels](https://github.com/orgs/hooroo/people).
- [ ] Your final merge commit message is in the format `<type>(<scope>): <description>` as per [the contributing guide](https://github.com/hooroo/roo-ui/blob/master/.github/CONTRIBUTING.md#commit-naming)
  - Example: `fix(dependencies): minor version bump to resolve security vulnerability in set-value`

2022-02-03 04:17 UTC, klubiniecki-qantas commented on src/components/TertiaryButton/README.md
> +| `align`    | align the button text | `left` / `right` | `left`  | -         |
Why not left / right / center? If we're doing the alignments, that should be easy to add.

2022-02-03 04:32 UTC, philipwindeyer commented on src/components/TertiaryButton/TertiaryButton.js
> +  align: 'left' | 'center',
README says left or right, but prop only allows for left or center?

2022-02-03 04:34 UTC, philipwindeyer requested changes
LGTM aside from the `align` options

2022-02-03 04:40 UTC, ryangaoqantashotels commented on src/components/TertiaryButton/README.md
> +| `align`    | align the button text | `left` / `right` | `left`  | -         |
I think it should only be left or center, I'll update it

2022-02-03 04:40 UTC, ryangaoqantashotels commented on src/components/TertiaryButton/TertiaryButton.js
> +  align: 'left' | 'center',
I think it should only be left or center, I'll update README

2022-02-03 04:55 UTC, klubiniecki-qantas commented on src/components/TertiaryButton/README.md
> +| `align`    | align the button text | `left` / `right` | `left`  | -         |
Please double check with Dani or Kym, doesn't make sense to do the work twice if it's needed. Other than that all good 🚀

2022-02-03 04:55 UTC, klubiniecki-qantas approved these changes

2022-02-03 05:43 UTC, philipwindeyer approved these changes
🚀  LGTM

2022-02-03 05:52 UTC, merged

2022-02-07 03:12 UTC, qh-deploy-user commented
:tada: This PR is included in version 0.127.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/roo-ui/v/0.127.0)
- [GitHub release](https://github.com/hooroo/roo-ui/releases/tag/v0.127.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: